name: Line limit

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  line-limit:
    uses: Glyndor/.github/.github/workflows/line-limit.yml@d4bbc5b6ec0c351ca4cb17d948ceaad818da4078 # v1.18.1
