name: guard

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  develop-only:
    uses: Glyndor/.github/.github/workflows/main-guard.yml@d4bbc5b6ec0c351ca4cb17d948ceaad818da4078 # v1.18.1
